config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'hello#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: :true
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_one_attached :photo
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
  has_many :tweets, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 }
  has_one_attached :photo

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :photo])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index

  end

  def link
    
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  def index
    @tweets = Tweet.all
    search = params[:search]
    @tweets = @tweets.where("body LIKE ?", "%#{search}%") if search.present?
    if params[:tag_ids]
      @tweets = []
      params[:tag_ids].each do |key, value|
        if value == "1"
          tag_tweets = Tag.find_by(name: key).tweets
          @tweets = @tweets.empty? ? tag_tweets : @tweets & tag_tweets
        end
      end
    end

    if params[:latest].present?
      @tweets = @tweets.order('created_at DESC')
    elsif params[:likes_count].present?
      @tweets = @tweets.sort {|a,b| b.liked_users.count <=> a.liked_users.count}
    end
    
    @tweets = Kaminari.paginate_array(@tweets).page(params[:page]).per(3)
    
    if params[:tag]
      Tag.create(name: params[:tag])
    end


  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body, :photo, :youtube_url, tag_ids: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def find_youtube_url(youtube_url)
    youtube_url = youtube_url.strip # strip!からstripに変更

    if youtube_url.include?("https://youtu.be/")
      youtube_url.gsub("https://youtu.be/", "")
      # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
    else
      youtube_url.gsub("https://www.youtube.com/watch?v=", "")
      # "https://www.youtube.com/watch?v=WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is GeekSalon.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geektwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7c59468f43.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1>GeekTwitter</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", tweets_path %></li>
        <li><%= link_to "新規投稿",new_tweet_path %></li>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>

  <div class="field">
      <%= f.label :youtube_url %><br>
      <%= f.text_field :youtube_url, :size => 140 %>
  </div>

  <div class="form_group">
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name ) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<h3>Tweet一覧</h3>
<%= link_to '新規投稿へ', new_tweet_path %>



<h3>投稿検索</h3>
  <%= form_tag({controller:"tweets", action:"index"},method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する' %>
  <% end %>
  <%= form_tag({controller:"tweets", action:"index"},method: :get) do %>
    <% Tag.all.each do |t| %>
      <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
    <% end %>
    <%= submit_tag '検索する' %>
  <% end %>

    <div class="button">
        <%= link_to '新しい順', tweets_path(request.params.merge({ latest: "true" })) %>
        <%= link_to '評価の高い順', tweets_path(likes_count: "true") %>
    </div>

<%= page_entries_info @tweets %>
<%= paginate @tweets %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <div class="main-box">
        <div class="left-container">
          <% if t.photo.attached? %>
            <%= image_tag t.photo, size: '250x200'%>
          <% end %>
          <% if t.user.photo.attached? %>
            <%= image_tag t.user.photo, size: '50x40'%>
          <% end %>
          <%= t.user.email %>
          <%= t.body %>
          <% t.tags.each do |tag| %>
            <span><%= tag.name %></span>
          <% end %>
        </div>
        <div class="right-container">
          <%= link_to "詳細", tweet_path(t.id) %>
          <% if user_signed_in? && current_user.id == t.user_id %>
            <%#= link_to "編集", edit_tweet_path(t.id) %>
            <%= link_to "削除する", tweet_path(t.id), data: { turbo_method: :delete } %>
                  <%= button_to "削除する", tweet_path(t.id), method: :delete %>

          <% end %> 
          <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
                <%= link_to tweet_like_path(id: t.id, tweet_id: t.id),data: { turbo_method: :delete } do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
            <% else %>
              <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), data: { turbo_method: :post } do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
            <% end %>
          <% else %>
            <p>いいねの数 = <%= t.likes.count %></p>
          <% end %>
        </div>
      </div>
        <p class="time"><%= t.created_at %></p>
    </div>
  <% end %>
</div>

<%= form_tag({controller:"tweets", action:"index"},method: :get) do %>
  <%= text_field_tag :tag %>
  <%= submit_tag 'タグ追加' %>
<% end %>

app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
  <p class="title">投稿フォーム</p>
  <%= form_for @tweet do |f| %>
    <div class="field">
      <%= f.label :投稿内容 %>
      <br>
      <%= f.text_field :body, :size => 140 %>
      <br>
    </div>

    <div class="field">
      <%= f.label :youtube_url %><br>
      <%= f.text_field :youtube_url, :size => 140 %>
    </div>

    <div class="field">
      <%= f.label :photo %>
      <%= f.file_field :photo %>
    </div>
    <div class="form_group">
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name ) do |tag| %>
        <div class="form-check">
          <%= tag.label class: 'form-check-label' do %>
            <%= tag.check_box class: 'form-check-input' %>
            <%= tag.text %>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= f.submit "送信" %>
    <br>
  <% end %>
</div>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h3>Tweet詳細</h3>
<div class="tweet">
  <% if @tweet.photo.attached? %>
      <%= image_tag @tweet.photo, size: '250x200'%>
  <% end %>
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
  <% if @tweet.youtube_url.present? %>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= find_youtube_url(@tweet.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <% end %>
  <% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.already_liked?(@tweet) %>
      <%= link_to tweet_like_path(@tweet),data: { turbo_method: :delete } do %>
        <i class="fas fa-heart"></i><%= @tweet.likes.count %>
      <% end %>
    <% else %>
      <%= link_to tweet_likes_path(@tweet), data: { turbo_method: :post } do %>
        <i class="far fa-heart"></i><%= @tweet.likes.count %>
      <% end %>
    <% end %>
  <% else %>
    <i class="far fa-heart"></i><%= @tweet.likes.count %>
  <% end %>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>


<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if @user.photo.attached? %>
      <%= image_tag @user.photo, size: '250x200'%>
  <% end %>

<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>
<!-- ここまで-->

<%= link_to "Tweet一覧に戻る", tweets_path %>